package com.myelin.client.util;


import org.slf4j.LoggerFactory;

import com.jcraft.jsch.Logger;

/**
 * Class to route log messages generated by JSch to Apache Commons Logging.
 * 
 * @author mrabbitt
 * @see com.jcraft.jsch.Logger
 */
public class JSchCommonsLogger implements Logger {
    private org.slf4j.Logger log;
    
    /**
     * Constructor with custom category name 
     * 
     * @param logName the category name used by this logger for Apache Commons.
     */
    public JSchCommonsLogger(String logName) {
        log = LoggerFactory.getLogger(logName);
    }
    
    /**
     * Default constructor
     */
    public JSchCommonsLogger() {
        this(Logger.class.getName());
    }

    /* (non-Javadoc)
     * @see com.jcraft.jsch.Logger#isEnabled(int)
     */
    public boolean isEnabled(int level) {
        switch (level) {
        case DEBUG:
            return log.isDebugEnabled();
        case INFO:
            return log.isInfoEnabled();
        case WARN:
            return log.isWarnEnabled();
        case ERROR:
            return log.isErrorEnabled();
        }
        return false;
    }

    /* (non-Javadoc)
     * @see com.jcraft.jsch.Logger#log(int, java.lang.String)
     */
    public void log(int level, String message) {
        switch (level) {
        case DEBUG:
            log.debug(message);
            break;
        case INFO:
            log.info(message);
            break;
        case WARN:
            log.warn(message);
            break;
        case ERROR:
            log.error(message);
            break;
        }
    }

}
